### ISSUE TITLE
[Feature request] add "prevent from sleep while downloading" option.

### ISSUE THREAD

**Issue by Nokia808** [inbasic/turbo-download-manager-v2#14]
I do not know if this is possible or not. But if it is possible then adding such feature will really being amazing for this nice add-on ......

**Comment by PiliGrass** [comment]
I second that. That would be  great feature. I have been using the extension all day, I really like it but, I keep having to adjust my power/sleep settings back and forth in order to keep it from sleeping. I am in a situation that every watt matters and it would be  great if I could just queue up some downloads and walk away knowing it will just finish then fall back on my normal settings. Thank you.

**Comment by sn0wyfall** [comment]
I'm not sure why it doesn't work for you, but it works like this for me. If files are downloading, then my Mac is prevented from falling asleep. 

However, this is also the case with paused downloads. This means that if you were downloading a 50MB file, and you lost your network connection at the 25MB mark, the download will pause but your computer will stay on until it drains all of its battery. My laptop drained a couple of times completely at inconvenient times over the last few months until I found out that this extension was causing it. What a horrendous bug.
